d = dict(name='孙悟空', age='18', gender='男')
a = dict(xm='sk', nn='19', bb='sk')
c = dict([('name', '孙悟饭'), ('age', 18)])
s = dict([('SK', 'SLL'), ('YYX', 'LLS')])
l = d.get('sk')
d = d.setdefault('agee', 'shangkang')
print(d)
print(a)
print(c)
print(s)
print(l)
print(d)
